### PR TITLE
Add openpmix/examples/dmodex.c test to CI.

### PR DESCRIPTION
**Pull request by awlauria**
Signed-off-by: Austen Lauria <awlauria@us.ibm.com>

### CODE REVIEW

**Comment by rhc54** [comment]
You'll want to grab the updated dmodex.c example from https://github.com/openpmix/prrte/pull/1242

**Comment by awlauria** [comment]
Thanks! - will update.

**Comment by awlauria** [comment]
bot:ibm:gnu:retest

**Comment by awlauria** [comment]
bot:ibm:retest

**Comment by awlauria** [comment]
bot:ibm:gnu:scale:retest

**Comment by awlauria** [comment]
bot:ibm:scale:retest

**Comment by awlauria** [comment]
bot:ibm:scale:retest

**Comment by awlauria** [comment]
bot:ibm:gnu:scale:retest

**Pull request merged**
