### PR TITLE
Add MPIR Shim to PRRTE level testing

### PR DESCRIPTION
**Pull request by jjhursey**
It's running the MPIR Shim CI test case for each PR to OpenPMIx and PRTE.

### CODE REVIEW

**Comment by jjhursey** [comment]
bot:ibm:retest

**Comment by jjhursey** [comment]
Any objections to bringing this in as a regular thing we test against PRTE and OpenPMIx PRs?
The request to do so came from the Open MPI community a while back - I just finally got around to it.

**Comment by rhc54** [comment]
If things look stable enough, then sure - we can give it a try.

**Comment by jjhursey** [comment]
I can re-run CI to double check with the current master branches before it's merged (it still needs a review):
bot:ibm:retest

**Comment by jjhursey** [comment]
File system glitch try again bot:ibm:retest

**Comment by jjhursey** [comment]
Looks like it passes fine with the master branch. Any objection to merging?

**Comment by rhc54** [comment]
No issue here - I can't really review, but I am okay as it passes and you are comfortable with it. Merge away!

**Pull request merged**
