### PR TITLE
Reenable debug tools CI test

### LINKED ISSUE #88: Re-enable the debugger PRRTE tests
We need to get the PRRTE debugger tests running again. They hit a signature issue last week and they had to be disabled.

To do:
- [ ] Fix baseline signatures in the pmix-tests branch
- [ ] Fix tests in PRRTE examples/debugger, as needed

Discussion context:
 * https://github.com/openpmix/openpmix/pull/2151
 * https://github.com/openpmix/pmix-tests/pull/86
 * https://github.com/openpmix/pmix-tests/pull/87

### PR DESCRIPTION
**Pull request by jjhursey**
Fixes #88

### CODE REVIEW

**Comment by jjhursey** [comment]
bot:ibm:retest

**Comment by jjhursey** [comment]
@drwootton CI is failing on the tools. It looks like an issue with the PID being reported. Can you take a look to see if this is an actual failure or an issue with the baselines/script?
 * https://gist.github.com/ibm-ompi/0c45b63232cbde169b23dde81038af7b

**Comment by drwootton** [comment]
I noticed a couple things. 
1) CI_NUM_NODES was set to 10, not 3, where CI_NUM_NODES=3 was the setting for the baseline. A different number of nodes will cause failures due to differences in number of app and daemon processes.
2) Pid is renamed in the baselines (to @PID&LT;n&GT;>) as an attempt to mask out different pids run to run. This looks like insufficient filtering since if multiple processes are forked on a node, the differences in order of launch can cause the compare to fail since pids are renamed to sequential numbers based on their order of appearance in the log. Based on order of forks, daemons and application processes can get their pids renamed differently.

**Comment by rhc54** [comment]
Something else you may need to consider here: the output from the application processes appears randomly interleaved as determined by time of arrival at `prterun`. So you may get a line from rank0, then a couple of lines from rank2, then a line from rank1, another line from rank0, etc. Output from your main program will be interleaved with the application proc output.

If your "signature" is looking to match output on a line-per-line basis, then you'll probably run into trouble due to this randomness. I don't know if you are doing so. Just wanted to ensure you were aware of the random interleaving factor.

**Comment by jjhursey** [comment]
bot:ibm:retest

**Comment by drwootton** [comment]
I identified three problems, variations in pid and which rank launches first on a node, variations in hostname due to which host launches tasks first, and random lost daemon output around daemon termination.

I solved the first by rewriting all pids with a constant string. I have partially solved the problem with variations in hostname and am still working on that.

I am seeing a problem with intermittent lost output from the daemons which is only happening with the multi-indirect testcases.

The tail of each daemon's output should be something like
~~~
daemon-0            : Waiting for application namespace @HOST<0>:@PID<?>:@NS<2> to terminate
daemon-0            : release_fn called as daemon callback for event=JOB ENDED
daemon-0            : DEBUGGER DAEMON NAMESPACE @HOST<0>:@PID<?>:@NS<0> NOTIFIED THAT JOB TERMINATED - AFFECTED @HOST<0>:@PID<?>:@NS<2>
daemon-0            : Application namespace @HOST<0>:@PID<?>:@NS<2> terminated
daemon-0            : Debugger daemon ns @HOST<0>:@PID<?>:@NS<0> rank 0 pid @PID<?>: Finalizing
~~~

The problem is that a daemon's output will be truncated anywhere after that first line above, randomly. Some daemon's output will be complete and others in the same run will lose output.

This is only a problem for the multi-node indirect tests. Multi-node attach, multi-node direct, and all single node tests work correctly, consistently.

I am wondering if there's a timing/synchronization problem between the daemons shutting down, the front end getting a lost connection event representing (I think) the loss of a connection for one or more, but not all of the daemons, and the stdio output flowing from the daemons back to the front end

The indirect-multi example terminates on receipt of the first lost connection event from any daemon.

Is there a way to force flush stdio output back to the front end before daemons shut down? I tried moving the fflush for stdout and stderr in the daemon before calling PMIx_tool_finalize, which did not seem to help.

Do I need some kind of a barrier in the daemon before the call to PMIx_tool_finalize? Is there an example of a crooss namespace barrier I could refer to, since I couldn't get that to work the last time I tried it. 

The random interleaving of application output should not be a problem. The tools, daemons, and hello application are all linked with an object file that wraps all of the printf functions that are used by these. 

The wrapper prefixes each output  line with tag composed of executable name, rank, and sequential number such as **daemon-1 :001:** **demon-1 :002:**, **daemon-2 :001** **daemon-2 :002**, etc. 

The output from a test is sorted based on these tags before it is compared to the baseline (since the tags are at the start of the line). The sequence numbers are stripped before comparison with the baseline to reduce noise when baseline comparisons fail.

This eliminates the problem of random interleaving, which does not matter since the tests are not looking for processes to run in a particular sequence.

**Comment by rhc54** [comment]
I can take a look next week at the multi-node indirect case - need to finish something else first. I imagine it is the output from daemons on compute nodes (i.e., not sharing the node with `prterun`) that is being lost - yes?

**Comment by jjhursey** [comment]
Commits from this were rolled into PR #102 so closing this PR.

**Comment by drwootton** [comment]
@jjhursey ran the CI test twice with my latest commits and did not have the problems with extra or missing output from the debug daemons that I was seeing pretty consistently.

Maybe this is something in my environment. My git logs say I have the latest commits as of today. One thing is I always build with --enable-debug, which should not affect anything.

Maybe we don't investigate this until this pops up in the CI tests.

**Comment by rhc54** [comment]
Makes sense - if we see it crop up, then worth looking at it as a separate issue.

**Comment by jjhursey** [comment]
It looks like the IO issue is cropping up with PRs intermittently. I filed a bug against PRTE to help track it (and refer folks to if they have questions about what CI is telling them):
  * https://github.com/openpmix/prrte/issues/1046

**Comment by rhc54** [comment]
Guess I'm a little confused - I tried running `indirect prterun --map-by ppr:1:node ./hello` and expected to see a daemon on each node. However, only one daemon started. So I'm guessing you are really saying that it is `indirect-multi` that is having the problem? Is the `multi` part of the name indicating `multi-node`?

It would probably help if you included a specific command line that is illustrating the behavior so I don't have to guess 😄

**Comment by rhc54** [comment]
I see what's going on - will have a fix later today or tomorrow.

**Comment by jjhursey** [comment]
In the output it prints the command just before the stdout/stderr check (first line below):
```
13:58:13 Starting testcase pid 10622: './indirect-multi --daemon-colocate-per-proc 1 prterun --hostfile hostfile_4_slots --np 12 ./hello '
13:58:16 Verify stdout/stderr for testcase indirect-colaunch2
69a70
> daemon-11           : release_fn called as daemon callback for event=JOB ENDED
122a124
> daemon-4            : release_fn called as daemon callback for event=JOB ENDED
152a155
> daemon-6            : release_fn called as daemon callback for event=JOB ENDED
167a171,173
> daemon-7            : release_fn called as daemon callback for event=JOB ENDED
> daemon-7            : DEBUGGER DAEMON NAMESPACE <host>:PID<?>:@NS<0> NOTIFIED THAT JOB TERMINATED - AFFECTED <host>:PID<?>:@NS<2>
> daemon-7            : Application namespace <host>:PID<?>:@NS<2> terminated
182a189,191
> daemon-8            : release_fn called as daemon callback for event=JOB ENDED
> daemon-8            : DEBUGGER DAEMON NAMESPACE <host>:PID<?>:@NS<0> NOTIFIED THAT JOB TERMINATED - AFFECTED <host>:PID<?>:@NS<2>
> daemon-8            : Application namespace <host>:PID<?>:@NS<2> terminated
```

I guess we don't print out the hostfile which we can do if you want. In this case it is:
```
shell$ cat hostfile_4_slots 
2e45a8d3bd07 slots=4
c8b1250da78b slots=4
25ed6e76e254 slots=4
```

**Pull request closed without merging**
