### PR TITLE
add "manystress" prrte test

### PR DESCRIPTION
**Pull request by naughtont3**
Signed-off-by: Thomas Naughton <naughtont@ornl.gov>
Signed-off-by: Wael Elwasif <elwasifwr@ornl.gov>

### CODE REVIEW

**Comment by jjhursey** [comment]
I added the `PRRTE_CI` label. That'll kick of the CI testing with this branch. So you can see if running it live causes any issues.
It should automatically kick off after every change.

**Comment by naughtont3** [comment]
Cool, that will be great.  How many nodes/cores are there on the default CI environment.  I just want to make sure the default values in the test are reasonable.

**Comment by naughtont3** [comment]
Is there a way to "test" the CI addition before merging it into master?  To ensure it works properly before merging to master.

**Comment by jjhursey** [comment]
CI usually runs 10 nodes - adjustable via the `CI_NUM_NODES` envar (the `CI_HOSTFILE` will have the hostfile if that is helpful). The CI nodes that I run on are 2 sockets x 10 cores x 8 hwthreads.

The 10 nodes are overloaded so timing might be a bit flexible.

Now that the `PRRTE_CI` label is on this PR then it'll run the `IBM CI (GNU/Scale)` bucket against PMIx and PRRTE master branches. We will just need to add this new directory to the listing in `prrte/.ci-tests` so CI knows that it is ok to run.

**Comment by naughtont3** [comment]
@jjhursey ok, so i changed the two parameters to scale based on the number of nodes.  I also added a new `CI_NUM_CORES_PER_NODE` that defaults to 20 in the script, but that way this can be tweaked via CI envvar if useful.

At this point I think it is ready to test for prrte CI.  If that all works, I'll squash commits.

BTW, I included a `misc/` subdir with slurm script for running this w/o CI environment and just reads values from slurm job info.  It is not required/used, but just wanted to keep things together.

**Comment by jjhursey** [comment]
All you need to do now is to edit `prrte/.ci-tests` and add the `manystress` to it:

```diff
  # PMIx Tool (Debugger) Unit Tests
  debug
+ # Add the Mini Stress Test
+ ministress
```

Once you commit that to this PR then CI will kick off and include running your test suite.
Thanks!

**Comment by jjhursey** [comment]
Sorry for the typo in my prior comment. It looks like CI is exercising it now. Let me know if you need any help debugging the backend.

**Comment by naughtont3** [comment]
bot:ibm:retest

**Comment by naughtont3** [comment]
bot:ibm:retest

**Comment by naughtont3** [comment]
bot:ibm:retest

**Comment by naughtont3** [comment]
bot:ibm:retest

**Comment by naughtont3** [comment]
Hmm, not sure why the children are waiting/hanging so that we are never able to reap them and finish.  A chunk of the background child processes (`prun sleeper | tee`) appear to not be exiting.  I've tried to add some debug but not sure how to figure out what is causing this.

The impact is test hits timeout.  The final checks show that there are a bunch of pid's that appear to still be alive (running).

For example, at the end i show the count of "alive" pids (`count=94`) and the values that I tried to verify by looking into `/proc` b/c there is no `ps` command available.

```
Thu Mar 18 18:20:01 UTC 2021 : 1616091601 : (count=94) ALIVE-LIST-ITEM: 28786
```

For now, just setting back to hardcoded number of procs and will see if this passes for now.

**Comment by jjhursey** [comment]
I added 'ps' to the build box image, so it should be there now if you want to try again.

**Comment by naughtont3** [comment]
OK, will give it another shot with larger number of tasks

**Comment by naughtont3** [comment]
bot:ibm:retest

**Comment by naughtont3** [comment]
So I was able to reproduce this locally using the `pmix-swarm-toy-box` environment.  What I found was that a small number of the `prun -np 1 ./sleeper x` instances hang.  This appears to be that the `PMIx_Spawn()` is blocking for some reason.  I see a `PMIx_Spawn()` failure at end when I CTRL+C top-level `run.sh` (parent) to teardown the run.   Question is, why does the spawn hang when trying to startup that process.

**Comment by naughtont3** [comment]
I did a bit more tracking and it appears the `sleeper` task does run, but for some reason the exit is not reported back to the waiting `prun` tool.  Thinking either wait cb missed the `SIGCHLD` from `sleeper` exit, or a notify message was lost over the docker overlay network. Both seem pretty unlikely, but latest debug changes for `sleeper` (not pushed yet) make it obvious when things have run and left an output dropping in filesystem.  Stopping here for the day.

**Comment by naughtont3** [comment]
Dump some notes here...

I changed the way we output things and can see that the problem is not with the remote execution of app (`sleeper`), but instead with the event notification at the client (`prun`). 

Brief synopsis:
 - Change to have `sleeper` open `/tmp/` file and write output directly with filename capturing hostname and launchID ($mycount).

 - Changed driver to loop like this:
  ```
    # nseconds  is seconds to sleep (random 1-10)
    # mycount   is unique ID for each instance we launch 
    _CMD="prun -n 1 ./sleeper $nseconds $mycount"

    # Launch prun without waiting (**background**)
   $_CMD &> /tmp/output.${mycount}.txt &
  ```
So can now see the output (or any errors) from `prun` and the `sleeper` separately.

Lastly, I instrumented code in `prun.c` to print the `"JOB %s COMPLETED WITH STATUS %d"`, and `"JOB %s EXECUTING (cmd=%s argv=%s)"`.

Observations:
 - Getting "hang" of some incomplete instances in test (e.g., `ps` shows waiting `prun` tool).
 - No pattern to host where problem occurs.
 - All of the `sleeper` apps ran (based on droppings in filesystem).
 - None of the `prun` tools that "hang" had any output in their log.  
 - The lack of `prun` output was because the `PMIx_Spawn()` in `prun` hangs so not print the job events.

While I have not tied immediately to the specific instances, I did notice that there are some DVM/server log errors, that appear at same count as the number of hangs.   The error is in `pmix_server_launch_resp()`.
```
[toynode01:76166] PRTE ERROR: Not found in file prted/pmix/pmix_server_dyn.c at line 96
```
Summary, thinking this is a failed/missing response on the spawn.  Maybe look into [https://github.com/openpmix/prrte/issues/344] as related.

I narrowed it down to errors for `prte_hotel_checkout_and_return_occupant()` which results in a `prun` hanging.   This presents as an error in DVM logs like [toynode01:76166] PRTE ERROR: Not found in file prted/pmix/pmix_server_dyn.c at line 96.   The jobid from unpacks look reasonable, but possibly problem with the `room` number (which is always 4094 or 4095).  I checked with Ralph and he mentioned that we reuse room once it is empty.

**Comment by rhc54** [comment]
I'll have to noodle over this a bit more. I'm not convinced my change in https://github.com/openpmix/prrte/pull/915 is going to resolve this, though I'm interested to hear an update. As mentioned in that PR, all interactions with the hotel appear to be taking place in events, so we should be "threadsafe" in that regard. However, it is possible that the object in the hotel is being tampered with outside of an event or in some race where it gets altered prior to checkout_and_return.

Will try and think of some way to check those possibilities.

**Comment by naughtont3** [comment]
@rhc54 OK, i'll see if it chances anything.  I'll also get things cleaned up so you can give it a test if helpful.  I'm able to reproduce the issue pretty much every time, number of hanging prun's differs, but always have a few.  Testing within Josh's docker-toybox utility.

**Comment by rhc54** [comment]
@naughtont3 I believe https://github.com/openpmix/prrte/pull/929 will fix the race condition issue. In short, the problem was the following code path:

* job A completes
* DVM notifies prun that job has completed and sets an event for cleanup
* prun receives job A completion notice and immediately issues spawn request for job B
* DVM receives job B request and enters a request into the hotel - however, the nspace in the request is INVALID at this point as the DVM has not yet begun the launch procedure
* DVM executes cleanup, which includes clearing the hotel of all pending requests related to job A. Unfortunately, since the nspace in the job B request is INVALID (which equates to WILDCARD), it gets included in the cleanup
* DVM spawns job B and attempts to notify prun of spawn complete, but cannot find the hotel occupant

It is that very small window between setting up the cleanup event and that event triggering that opened the door. Root cause is the cleanup treating INVALID as WILDCARD. I've closed both of those out.

**Comment by naughtont3** [comment]
@rhc54 Yes, I think you got it with https://github.com/openpmix/prrte/pull/929.  I re-ran several times and all ran as expected, where previously a few Spawn's would hang.   I will cleanup debugs and kickoff another run of things on the live CI environment. Thanks Ralph!

**Comment by naughtont3** [comment]
bot:ibm:retest

**Comment by naughtont3** [comment]
I squashed history and believe all ready now.  Only item remaining would be cleanup of /tmp droppings on remote nodes.  Not sure if that matters for CI runs.  If so, there's a suggested approach in `clean.sh` that is commented out at the moment.

**Comment by naughtont3** [comment]
Sigh.  Well there was some error for two instances, they ran but no output in outlog.  Maybe I should leave `DEBUG` enabled?  I'm tempted to just leave this as a manual test and not run with CI by default.

**Comment by jjhursey** [comment]
The IBM CI setup uses a private virtual cluster per PR. So you don't need to clean up `/tmp` as it will be cleaned once the test is done.

**Comment by naughtont3** [comment]
> The IBM CI setup uses a private virtual cluster per PR. So you don't need to clean up `/tmp` as it will be cleaned once the test is done.

OK, thanks @jjhursey .  Then I'm inclined to not worry about the `/tmp` cleanup for those remote nodes.

**Comment by naughtont3** [comment]
bot:ibm:retest

**Comment by naughtont3** [comment]
As per discussion today, remove WIP label and off by default in `.ci-tests` list.

**Pull request merged**
